# SelectoMix Configuration for SelectoTest
version: "1.0"

# Default settings for all environments
defaults:
  adapter: postgres
  validate: true
  associations: true
  joins: advanced
  join_depth: 4
  join_strategy: optimized
  detect_cycles: true

# Database adapter configurations
adapters:
  postgres:
    extensions: [uuid-ossp, ltree, pgcrypto]
    version: "14.0"
  mysql:
    version: "8.0"
    charset: utf8mb4
    collation: utf8mb4_unicode_ci
  sqlite:
    extensions: [json1, fts5]
    journal_mode: wal
    foreign_keys: on

# Code generation settings
generation:
  output: lib/selecto_test/selecto_domains
  style: modular
  format: documented
  namespace: SelectoTest.Selecto
  
  features:
    custom_columns: true
    filters: true
    aggregates: true
    saved_views: true
    tests: true
    migrations: false
    live: true

# Template customization
templates:
  override_path: priv/selecto_templates
  use_custom: false
  
# Environment-specific overrides
environments:
  development:
    adapter: postgres
    validate: false
    generation:
      format: expanded
      tests: false
      
  test:
    adapter: sqlite
    validate: false
    generation:
      output: lib/selecto_test/selecto_test
      tests: true
      migrations: true
      
  production:
    adapter: postgres
    validate: true
    generation:
      format: compact
      optimize: true

# Named profiles for common scenarios
profiles:
  minimal:
    associations: false
    joins: none
    generation:
      features:
        custom_columns: false
        filters: false
        aggregates: false
        saved_views: false
        tests: false
        migrations: false
        live: false
        
  ecommerce:
    # Optimized for our e-commerce schema
    joins: advanced
    join_depth: 5
    generation:
      features:
        custom_columns: true
        filters: true
        aggregates: true
        saved_views: true
        tests: true
        migrations: true
        live: true
    # Special handling for complex relationships
    special_schemas:
      - SelectoTest.Ecommerce.User      # Has hierarchical referrals
      - SelectoTest.Ecommerce.Category   # Has hierarchical categories
      - SelectoTest.Ecommerce.UserHistory # SCD Type 2 dimension
      
  mysql_migration:
    # Profile for migrating to MySQL
    adapter: mysql
    generation:
      migrations: true
      features:
        arrays_as_json: true
        uuid_as_string: true
        
  sqlite_dev:
    # Quick SQLite development setup
    adapter: sqlite
    generation:
      output: lib/selecto_test/sqlite_domains
      features:
        tests: false
        live: false