# SelectoMix MySQL-Specific Configuration
version: "1.0"

# MySQL-focused configuration
defaults:
  adapter: mysql
  validate: true
  associations: true
  joins: advanced
  join_depth: 3  # Reduced for MySQL performance
  join_strategy: lazy  # Better for MySQL
  detect_cycles: true

adapters:
  mysql:
    version: "8.0.32"
    charset: utf8mb4
    collation: utf8mb4_unicode_ci
    # MySQL-specific settings
    strict_mode: true
    sql_mode: "TRADITIONAL"
    # Features available in this version
    features:
      ctes: true          # Available in 8.0+
      window_functions: true  # Available in 8.0+
      json_table: true    # For array handling
      check_constraints: true  # 8.0.16+

generation:
  output: lib/selecto_test/mysql_domains
  style: modular
  format: documented
  namespace: SelectoTest.MySQL
  
  # MySQL-specific generation features
  features:
    custom_columns: true
    filters: true
    aggregates: true
    saved_views: false  # No materialized views in MySQL
    tests: true
    migrations: true
    live: true
    
  # MySQL-specific adaptations
  adaptations:
    arrays_as_json: true
    uuid_as_varchar: true
    boolean_as_tinyint: true
    text_search_fulltext: true
    
  # Index generation for MySQL
  indexes:
    foreign_keys: true
    unique_constraints: true
    fulltext: true
    spatial: false

# MySQL-specific type mappings
type_mappings:
  uuid: varchar(36)
  binary_id: varchar(36)
  array: json
  jsonb: json
  macaddr: varchar(17)
  inet: varchar(45)
  cidr: varchar(45)
  ltree: text
  
# Migration helpers for MySQL
migration_helpers:
  uuid_generation: "UUID()"
  timestamp_default: "CURRENT_TIMESTAMP"
  json_default: "'[]'"
  
environments:
  development:
    adapter: mysql
    validate: false
    connection:
      host: localhost
      port: 3306
      database: selecto_test_dev
      
  test:
    adapter: mysql
    validate: false
    connection:
      host: localhost
      port: 3306
      database: selecto_test_test
      
  production:
    adapter: mysql
    validate: true
    connection:
      host: ${MYSQL_HOST}
      port: ${MYSQL_PORT}
      database: ${MYSQL_DATABASE}
    generation:
      format: compact
      optimize: true

profiles:
  performance:
    # Optimized for MySQL performance
    join_strategy: lazy
    join_depth: 2
    generation:
      indexes:
        covering_indexes: true
        composite_indexes: true
      optimizations:
        query_cache: true
        result_cache: true
        
  compatibility:
    # Maximum compatibility with older MySQL versions
    adapters:
      mysql:
        version: "5.7"
        features:
          ctes: false
          window_functions: false
          check_constraints: false
    generation:
      adaptations:
        use_legacy_syntax: true